apiVersion: apps/v1
kind: Deployment
metadata:
  name: uade-webapp
  labels:
    app: uade-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uade-app
  template:
    metadata:
      labels:
        app: uade-app
    spec:
      containers:
      - name: uade-app
        image: uade-aa-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: uade-app-service
spec:
  type: NodePort
  selector:
    app: uade-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30100